### PR TITLE
the completed version of form

### LINKED ISSUE #128: code refactor error form in router.js

### LINKED ISSUE #146: value form no number but name

### LINKED ISSUE #147: value in .ejs doesnot match with database

### LINKED ISSUE #180: Localstorage not completely working right

### LINKED ISSUE #182: Theme dropdown when refreshed, not working

### LINKED ISSUE #189: change all px to em in form

### LINKED ISSUE #198: display label instead of id in the themes input field

### LINKED ISSUE #199: code for form in script.js export to form.js

### LINKED ISSUE #200: extra validation for theme's (choose max number of theme's)

### LINKED ISSUE #201: Dialog styling, img container and close buttons styling

### PR DESCRIPTION
**Pull request by laibaaac**
every bug is gone, just to be sure, watch out for the script.js

### CODE REVIEW

File: routes/route.js [hunk 1]
```diff
@@ -368,9 +368,9 @@ router.post("/form", async (req, res) => {
       title: "sent",
     });
   } catch (error) {
```
Comment (RainbowJM) [inline routes/route.js:370]: Why do you have dubbele error handling?

**Review by RainbowJM — CHANGES_REQUESTED** [review]
Check review

**Review by RainbowJM — APPROVED** [review]
lgtm
